"use strict";

const crypto = require("crypto");
const { spawn } = require("child_process");

const START_TIMEOUT_MS = 30_000;
const STOP_GRACE_MS = 5_000;

function readyPort(line) {
  const match = String(line || "").match(/HERMES_DASHBOARD_READY\s+port=(\d+)/);
  const port = match ? Number(match[1]) : 0;
  return Number.isInteger(port) && port > 0 && port <= 65535 ? port : 0;
}

// Native mode owns a private loopback Gateway. The token is generated by Hub,
// passed only to the child environment, and never leaves this process.
function createHermesNativeRuntime({ resolveHermesBin, cwd, spawnImpl = spawn } = {}) {
  let child = null;
  let startPromise = null;
  let connection = null;

  async function start() {
    if (connection) return connection;
    if (startPromise) return startPromise;
    startPromise = (async () => {
      const bin = await resolveHermesBin();
      if (!bin) {
        throw new Error("hermes executable is unavailable for native mode");
      }
      return new Promise((resolve, reject) => {
        const token = crypto.randomBytes(32).toString("base64url");
        let settled = false;
        let output = "";
        const finish = (error, value) => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          startPromise = null;
          if (error) reject(error);
          else resolve(value);
        };
        const timer = setTimeout(() => {
          try { child && child.kill("SIGTERM"); } catch {}
          finish(new Error("Hermes native Gateway did not become ready"));
        }, START_TIMEOUT_MS);
        try {
          child = spawnImpl(bin, ["serve", "--host", "127.0.0.1", "--port", "0", "--skip-build"], {
            argv0: "prism-hermes-native",
            cwd,
            env: { ...process.env, HERMES_DASHBOARD_SESSION_TOKEN: token },
            stdio: ["ignore", "pipe", "pipe"],
          });
          const consume = (chunk) => {
            output = `${output}${String(chunk || "")}`.slice(-16_384);
            const port = readyPort(output);
            if (!port) return;
            connection = { wsUrl: `ws://127.0.0.1:${port}/api/ws?token=${encodeURIComponent(token)}`, port, pid: child.pid || 0 };
            finish(null, connection);
          };
          child.stdout.setEncoding("utf8");
          child.stderr.setEncoding("utf8");
          child.stdout.on("data", consume);
          child.stderr.on("data", consume);
          child.once("error", (error) => finish(error));
          child.once("close", (code) => {
            const active = child;
            child = null;
            connection = null;
            if (!settled) finish(new Error(`Hermes native Gateway exited before ready (code ${code ?? "unknown"})`));
            if (active) startPromise = null;
          });
        } catch (error) {
          finish(error instanceof Error ? error : new Error(String(error)));
        }
      });
    })();
    return startPromise;
  }

  async function close() {
    const running = child;
    child = null;
    connection = null;
    startPromise = null;
    if (!running || running.exitCode !== null || running.killed) return;
    await new Promise((resolve) => {
      const killTimer = setTimeout(() => {
        try { running.kill("SIGKILL"); } catch {}
      }, STOP_GRACE_MS);
      running.once("close", () => {
        clearTimeout(killTimer);
        resolve();
      });
      try { running.kill("SIGTERM"); } catch { clearTimeout(killTimer); resolve(); }
    });
  }

  return {
    start,
    connection: start,
    close,
    pid: () => connection && connection.pid || 0,
  };
}

module.exports = { createHermesNativeRuntime, readyPort };
